export {
	Container,
	ModalContainer,
	Loader,
	ModalHeader,
	ModalProfileDiv,
	ModalMediaSectionContainer,
	ModalTextarea,
	Textarea,
	TextareaPlaceHolder,
	ModalMediaarea,
	AddPhotoContainer,
	AddPhotoInput,
	ModalBottomSectionContainer,
	AddMediaToPost,
	ModalSubmitButton,
} from "./modals.styled";
