import {
	Container,
	ModalContainer,
	ModalHeader,
	ModalProfileDiv,
	ModalMediaSectionContainer,
	ModalTextarea,
	Textarea,
	TextareaPlaceHolder,
	ModalMediaarea,
	AddPhotoContainer,
	AddPhotoInput,
	ModalBottomSectionContainer,
	AddMediaToPost,
	ModalSubmitButton,
} from "./addPost.styled";

export {
	Container,
	ModalContainer,
	ModalHeader,
	ModalProfileDiv,
	ModalMediaSectionContainer,
	ModalTextarea,
	Textarea,
	TextareaPlaceHolder,
	ModalMediaarea,
	AddPhotoContainer,
	AddPhotoInput,
	ModalBottomSectionContainer,
	AddMediaToPost,
	ModalSubmitButton,
};
